FROM python:3.12-slim

RUN pip install pipenv

WORKDIR /app

COPY ["Pipfile", "Pipfile.lock", "./"]

#Install it as part of the system not venv inside of system
RUN pipenv install --system --deploy

COPY ./model ./model

COPY ./streamlit-app ./streamlit-app

WORKDIR /app/streamlit-app

EXPOSE 8501

CMD ["streamlit", "run", "app-showdown.py", "--server.port=8501", "--server.address=0.0.0.0"]

